/**
 * Australian trading names (brands people work for), not legal entity suffixes.
 * Compiled from major private employers, ASX consumer brands, government
 * entities and branches, AU/NZ local councils, health, education,
 * established vehicle and machinery OEMs, professional services and
 * hospitality. Free-typed names still save; this list only powers
 * predictive text.
 */

function rec(name, aliases = [], sector = "") {
  return {
    name,
    aliases: aliases.map((a) => String(a).toLowerCase()),
    sector,
  };
}

const EMPLOYERS = [
  // Supermarkets & everyday retail
  rec("Woolworths", ["wow", "woolies", "woolworths supermarket"], "retail"),
  rec("Big W", ["bigw"], "retail"),
  rec("Everyday Extra", ["everyday market"], "retail"),
  rec("Coles", ["coles supermarket", "coles group"], "retail"),
  rec("Liquorland", ["liquor land"], "retail"),
  rec("First Choice Liquor", ["first choice"], "retail"),
  rec("ALDI", ["aldi australia"], "retail"),
  rec("IGA", ["independent grocers"], "retail"),
  rec("Foodland", [], "retail"),
  rec("Foodworks", [], "retail"),
  rec("Harris Farm Markets", ["harris farm"], "retail"),
  rec("Costco", ["costco australia"], "retail"),
  rec("Metcash", ["iga distribution"], "retail"),

  // Wesfarmers brands (trading names)
  rec("Bunnings", ["bunnings warehouse"], "retail"),
  rec("Kmart", ["kmart australia"], "retail"),
  rec("Target", ["target australia"], "retail"),
  rec("Officeworks", [], "retail"),
  rec("Catch", ["catch.com.au"], "retail"),
  rec("Kleenheat", [], "energy"),

  // Department, fashion, specialty
  rec("Myer", [], "retail"),
  rec("David Jones", ["djones"], "retail"),
  rec("JB Hi-Fi", ["jb hifi", "jbhifi"], "retail"),
  rec("The Good Guys", ["good guys"], "retail"),
  rec("Harvey Norman", ["domayne", "joyce mayne"], "retail"),
  rec("Domayne", [], "retail"),
  rec("Supercheap Auto", ["super cheap auto"], "retail"),
  rec("Rebel", ["rebel sport"], "retail"),
  rec("BCF", ["boating camping fishing"], "retail"),
  rec("Macpac", [], "retail"),
  rec("Cotton On", ["cotton on group", "factorie", "rubi"], "retail"),
  rec("Country Road", ["witchery", "mimco", "trenery"], "retail"),
  rec("The Reject Shop", [], "retail"),
  rec("Chemist Warehouse", ["chemistwarehouse"], "retail"),
  rec("Priceline", ["priceline pharmacy"], "retail"),
  rec("TerryWhite Chemmart", ["terry white"], "retail"),
  rec("Amcal", [], "retail"),
  rec("Bloom", ["bloom hair"], "retail"),

  // Banks & insurers
  rec("Commonwealth Bank", ["cba", "commbank"], "banking"),
  rec("Westpac", ["westpac banking"], "banking"),
  rec("St George", ["st george bank"], "banking"),
  rec("Bank of Melbourne", [], "banking"),
  rec("BankSA", ["bank sa"], "banking"),
  rec("NAB", ["national australia bank"], "banking"),
  rec("ANZ", ["anz bank"], "banking"),
  rec("Macquarie", ["macquarie bank", "macquarie group"], "banking"),
  rec("ING", ["ing australia"], "banking"),
  rec("Bendigo Bank", ["bendigo and adelaide"], "banking"),
  rec("Bank of Queensland", ["boq"], "banking"),
  rec("Suncorp", ["suncorp bank"], "banking"),
  rec("AMP", [], "banking"),
  rec("ME Bank", ["me bank"], "banking"),
  rec("HSBC", ["hsbc australia"], "banking"),
  rec("Citibank", ["citi australia"], "banking"),
  rec("Allianz", ["allianz australia"], "insurance"),
  rec("QBE", [], "insurance"),
  rec("IAG", ["nrma insurance", "sgio", "sgic"], "insurance"),
  rec("NRMA", ["nrma insurance"], "insurance"),
  rec("RACV", [], "insurance"),
  rec("RACQ", [], "insurance"),
  rec("RAA", [], "insurance"),
  rec("Medibank", ["medibank private"], "insurance"),
  rec("Bupa", ["bupa australia"], "insurance"),
  rec("HCF", [], "insurance"),
  rec("NIB", [], "insurance"),
  rec("HBF", [], "insurance"),

  // Telco & tech
  rec("Telstra", ["telstra group"], "telco"),
  rec("Optus", ["singtel optus"], "telco"),
  rec("Vodafone", ["tpn vodafone", "vodafone australia"], "telco"),
  rec("TPG", ["tpg telecom"], "telco"),
  rec("Belong", [], "telco"),
  rec("iiNet", ["iinet"], "telco"),
  rec("Aussie Broadband", [], "telco"),
  rec("Atlassian", [], "tech"),
  rec("Canva", [], "tech"),
  rec("Xero", [], "tech"),
  rec("MYOB", [], "tech"),
  rec("WiseTech Global", ["wisetech"], "tech"),
  rec("TechnologyOne", ["technology one"], "tech"),
  rec("Microsoft", ["microsoft australia"], "tech"),
  rec("Google", ["google australia", "alphabet"], "tech"),
  rec("Amazon", ["amazon australia", "aws", "amazon web services"], "tech"),
  rec("Meta", ["facebook australia"], "tech"),
  rec("IBM", ["ibm australia"], "tech"),
  rec("Salesforce", [], "tech"),
  rec("Oracle", ["oracle australia"], "tech"),
  rec("SAP", ["sap australia"], "tech"),
  rec("Apple", ["apple australia"], "tech"),

  // Resources & energy
  rec("BHP", ["bhp group"], "resources"),
  rec("Rio Tinto", ["rio"], "resources"),
  rec("Fortescue", ["fmg", "fortescue metals"], "resources"),
  rec("Hancock Prospecting", ["hancock"], "resources"),
  rec("Newmont", ["newcrest"], "resources"),
  rec("South32", [], "resources"),
  rec("Mineral Resources", ["minres"], "resources"),
  rec("Northern Star", [], "resources"),
  rec("Evolution Mining", [], "resources"),
  rec("Yancoal", [], "resources"),
  rec("Glencore", ["glencore australia"], "resources"),
  rec("Woodside", ["woodside energy"], "energy"),
  rec("Santos", [], "energy"),
  rec("Origin Energy", ["origin"], "energy"),
  rec("AGL", ["agl energy"], "energy"),
  rec("EnergyAustralia", ["energy australia"], "energy"),
  rec("Alinta Energy", ["alinta"], "energy"),
  rec("Ampol", ["caltex"], "energy"),
  rec("BP", ["bp australia"], "energy"),
  rec("Shell", ["shell australia"], "energy"),
  rec("United Petroleum", ["united"], "energy"),
  rec("7-Eleven", ["7 eleven", "seven eleven"], "retail"),

  // Health
  rec("NSW Health", ["nsw health", "health nsw"], "health"),
  rec("Queensland Health", ["qld health"], "health"),
  rec("SA Health", [], "health"),
  rec("WA Health", ["health department wa"], "health"),
  rec("Victorian Department of Health", ["safer care victoria"], "health"),
  rec("Tasmanian Health Service", ["ths"], "health"),
  rec("Canberra Health Services", [], "health"),
  rec("Ramsay Health Care", ["ramsay"], "health"),
  rec("Healthscope", [], "health"),
  rec("St Vincent's Health", ["st vincents"], "health"),
  rec("Mater", ["mater health"], "health"),
  rec("Sonic Healthcare", ["douglass hanly moir", "sullivan nicolaides"], "health"),
  rec("Healius", ["lavertys", "qml"], "health"),
  rec("CSL", ["csl behring", "seqirus"], "health"),
  rec("Cochlear", [], "health"),
  rec("ResMed", [], "health"),
  rec("Icon Cancer Centre", ["icon group"], "health"),

  // Government & education
  rec("Australian Public Service", ["aps", "australian government"], "government"),
  rec("Services Australia", ["centrelink", "medicare office", "child support"], "government"),
  rec("Centrelink", ["centrelink office"], "government"),
  rec("Medicare", ["medicare australia"], "government"),
  rec("Child Support", ["child support agency"], "government"),
  rec("Australian Taxation Office", ["ato"], "government"),
  rec("Department of Defence", ["defence", "adf", "australian defence force"], "government"),
  rec("Australian Army", ["army australia"], "government"),
  rec("Royal Australian Navy", ["ran", "navy australia"], "government"),
  rec("Royal Australian Air Force", ["raaf", "air force australia"], "government"),
  rec("Australian Federal Police", ["afp"], "government"),
  rec("Australian Border Force", ["abf", "customs"], "government"),
  rec("Department of Home Affairs", ["home affairs"], "government"),
  rec("Department of Foreign Affairs and Trade", ["dfat", "austrade"], "government"),
  rec("Department of the Treasury", ["treasury australia"], "government"),
  rec("Department of Finance", ["finance australia"], "government"),
  rec("Department of the Prime Minister and Cabinet", ["pmc", "pm&c"], "government"),
  rec("Attorney-General's Department", ["attorney general", "agd"], "government"),
  rec("Department of Social Services", ["dss"], "government"),
  rec("Department of Health and Aged Care", ["health australia", "aged care"], "government"),
  rec("Department of Education", ["education australia"], "government"),
  rec("Department of Employment and Workplace Relations", ["dewr", "fair work"], "government"),
  rec("Department of Climate Change, Energy, the Environment and Water", ["dcceew"], "government"),
  rec("Department of Infrastructure, Transport, Regional Development, Communications and the Arts", ["infrastructure australia", "ditrdca"], "government"),
  rec("Department of Industry, Science and Resources", ["industry australia", "disr"], "government"),
  rec("Department of Agriculture, Fisheries and Forestry", ["daff", "agriculture australia"], "government"),
  rec("Department of Veterans' Affairs", ["dva"], "government"),
  rec("National Indigenous Australians Agency", ["niaa"], "government"),
  rec("NDIA", ["ndis", "national disability insurance"], "government"),
  rec("CSIRO", [], "government"),
  rec("Bureau of Meteorology", ["bom", "weather bureau"], "government"),
  rec("Geoscience Australia", [], "government"),
  rec("Australian Bureau of Statistics", ["abs"], "government"),
  rec("Australian Electoral Commission", ["aec"], "government"),
  rec("ASIC", ["australian securities and investments"], "government"),
  rec("ACCC", ["australian competition and consumer"], "government"),
  rec("APRA", ["australian prudential"], "government"),
  rec("Reserve Bank of Australia", ["rba"], "government"),
  rec("Fair Work Ombudsman", ["fwo"], "government"),
  rec("Fair Work Commission", ["fwc"], "government"),
  rec("Comcare", [], "government"),
  rec("Safe Work Australia", ["safework australia"], "government"),
  rec("CASA", ["civil aviation safety authority"], "government"),
  rec("AMSA", ["australian maritime safety"], "government"),
  rec("IP Australia", ["ip australia"], "government"),
  rec("NBN Co", ["nbn"], "government"),
  rec("Snowy Hydro", ["snowy hydro"], "government"),
  rec("Future Fund", [], "government"),
  rec("NSW Police", ["nsw police force"], "government"),
  rec("Victoria Police", ["vicpol"], "government"),
  rec("Queensland Police", ["qps", "queensland police service"], "government"),
  rec("WA Police", ["wapol", "western australia police"], "government"),
  rec("SA Police", ["sapol"], "government"),
  rec("Tasmania Police", [], "government"),
  rec("NT Police", ["nt police fire and emergency"], "government"),
  rec("ACT Policing", ["act police"], "government"),
  rec("Australia Post", ["auspost"], "government"),
  rec("ABC", ["australian broadcasting corporation"], "media"),
  rec("SBS", [], "media"),
  rec("Service NSW", ["service nsw"], "government"),
  rec("Transport for NSW", ["tfNSW", "tfnsw", "sydney trains", "sydney metro"], "government"),
  rec("NSW Ambulance", ["ambulance nsw"], "government"),
  rec("Fire and Rescue NSW", ["frnsw"], "government"),
  rec("NSW Rural Fire Service", ["rfs", "nsw rfs"], "government"),
  rec("NSW SES", ["state emergency service nsw"], "government"),
  rec("Corrective Services NSW", ["csnsw"], "government"),
  rec("Revenue NSW", ["office of state revenue"], "government"),
  rec("Sydney Water", [], "government"),
  rec("Hunter Water", [], "government"),
  rec("Ausgrid", [], "government"),
  rec("Endeavour Energy", [], "government"),
  rec("Essential Energy", [], "government"),
  rec("SafeWork NSW", ["safework nsw"], "government"),
  rec("National Parks and Wildlife Service", ["npws"], "government"),
  rec("Service Victoria", [], "government"),
  rec("Department of Transport and Planning Victoria", ["vic roads", "vicroads"], "government"),
  rec("VicRoads", ["vic roads"], "government"),
  rec("Ambulance Victoria", ["av ambulance"], "government"),
  rec("Fire Rescue Victoria", ["frv"], "government"),
  rec("CFA", ["country fire authority"], "government"),
  rec("SES Victoria", ["vic ses"], "government"),
  rec("WorkSafe Victoria", ["worksafe vic"], "government"),
  rec("Parks Victoria", [], "government"),
  rec("Melbourne Water", [], "government"),
  rec("Yarra Valley Water", [], "government"),
  rec("South East Water", [], "government"),
  rec("Metro Trains Melbourne", ["metro trains"], "government"),
  rec("Yarra Trams", [], "government"),
  rec("V/Line", ["vline"], "government"),
  rec("Service Queensland", ["smart service queensland"], "government"),
  rec("TMR", ["transport and main roads", "dtmr"], "government"),
  rec("Queensland Rail", ["qr"], "government"),
  rec("Queensland Ambulance Service", ["qas"], "government"),
  rec("QFES", ["queensland fire and emergency"], "government"),
  rec("Seqwater", [], "government"),
  rec("Urban Utilities", ["queensland urban utilities"], "government"),
  rec("Energex", [], "government"),
  rec("Ergon Energy", ["ergon"], "government"),
  rec("Powerlink", ["powerlink queensland"], "government"),
  rec("Main Roads WA", ["mainroads"], "government"),
  rec("PTA WA", ["transperth", "public transport authority"], "government"),
  rec("DFES", ["department of fire and emergency services"], "government"),
  rec("St John Ambulance WA", ["st john wa"], "government"),
  rec("Water Corporation", ["water corporation wa"], "government"),
  rec("Synergy", ["synergy wa"], "government"),
  rec("Western Power", [], "government"),
  rec("ServiceWA", ["service wa"], "government"),
  rec("Service SA", [], "government"),
  rec("SA Ambulance Service", ["saas"], "government"),
  rec("Metropolitan Fire Service", ["mfs adelaide"], "government"),
  rec("SA Water", [], "government"),
  rec("SA Power Networks", ["sapn"], "government"),
  rec("Department of State Growth", ["state growth tasmania"], "government"),
  rec("TasWater", [], "government"),
  rec("TasNetworks", [], "government"),
  rec("ACT Government", ["act gov", "canberra government"], "government"),
  rec("Access Canberra", [], "government"),
  rec("Transport Canberra", ["action buses"], "government"),
  rec("Icon Water", [], "government"),
  rec("Power and Water", ["power and water nt"], "government"),

  rec("New Zealand Public Service", ["nz government", "te kawa mataaho"], "government"),
  rec("Inland Revenue", ["ird", "inland revenue nz"], "government"),
  rec("Ministry of Social Development", ["msd", "work and income", "winz"], "government"),
  rec("Health New Zealand", ["te whatu ora", "ministry of health nz"], "government"),
  rec("Ministry of Education", ["education nz", "tāhurangi"], "government"),
  rec("New Zealand Police", ["nz police", "nga pirihimana"], "government"),
  rec("New Zealand Defence Force", ["nzdf", "defence nz"], "government"),
  rec("New Zealand Army", ["nz army"], "government"),
  rec("Royal New Zealand Navy", ["rnzn", "navy nz"], "government"),
  rec("Royal New Zealand Air Force", ["rnzaf", "air force nz"], "government"),
  rec("Department of Conservation", ["doc", "doc nz"], "government"),
  rec("MBIE", ["ministry of business innovation and employment"], "government"),
  rec("Waka Kotahi", ["nzta", "nz transport agency"], "government"),
  rec("ACC", ["accident compensation corporation"], "government"),
  rec("Fire and Emergency New Zealand", ["fenz"], "government"),
  rec("NZ Customs", ["new zealand customs"], "government"),
  rec("Immigration New Zealand", ["inz"], "government"),
  rec("Kāinga Ora", ["kainga ora", "housing nz"], "government"),
  rec("KiwiRail", [], "government"),
  rec("NZ Post", ["new zealand post"], "government"),
  rec("Transpower", [], "government"),
  rec("WorkSafe New Zealand", ["worksafe nz"], "government"),
  rec("Stats NZ", ["tatauranga aotearoa"], "government"),
  rec("Ministry for Primary Industries", ["mpi"], "government"),
  rec("Ministry for the Environment", ["mfe"], "government"),
  rec("The Treasury", ["treasury nz"], "government"),
  rec("Department of Internal Affairs", ["dia"], "government"),
  rec("Ministry of Justice", ["justice nz"], "government"),
  rec("Ara Poutama Aotearoa", ["corrections nz", "department of corrections"], "government"),
  rec("Oranga Tamariki", ["ministry for children"], "government"),
  rec("Te Puni Kōkiri", ["te puni kokiri", "ministry of maori development"], "government"),
  rec("Pharmac", ["pharmaceutical management agency"], "government"),
  rec("NIWA", ["national institute of water and atmospheric"], "government"),
  rec("GNS Science", ["gns"], "government"),
  rec("MetService", ["metservice nz"], "government"),
  rec("Maritime New Zealand", ["maritime nz"], "government"),
  rec("Civil Aviation Authority", ["caa nz"], "government"),
  rec("Air New Zealand", ["air nz"], "aviation"),
  rec("Auckland Transport", ["at auckland"], "government"),

  // Local government — capitals, metro and well-known regional councils (AU + NZ)
  rec("City of Sydney", ["sydney council", "sydney city council"], "government"),
  rec("Inner West Council", ["inner west"], "government"),
  rec("City of Parramatta", ["parramatta council"], "government"),
  rec("Blacktown City Council", ["blacktown council"], "government"),
  rec("Canterbury-Bankstown Council", ["cbcity", "bankstown council", "canterbury council"], "government"),
  rec("Liverpool City Council", ["liverpool council"], "government"),
  rec("Penrith City Council", ["penrith council"], "government"),
  rec("Northern Beaches Council", ["northern beaches"], "government"),
  rec("Sutherland Shire Council", ["sutherland shire"], "government"),
  rec("Wollongong City Council", ["wollongong council"], "government"),
  rec("City of Newcastle", ["newcastle council"], "government"),
  rec("Central Coast Council", ["central coast nsw"], "government"),
  rec("Lake Macquarie City Council", ["lake macquarie council"], "government"),
  rec("City of Randwick", ["randwick council"], "government"),
  rec("The Hills Shire Council", ["the hills council"], "government"),
  rec("Cumberland City Council", ["cumberland council"], "government"),
  rec("Campbelltown City Council", ["campbelltown council"], "government"),
  rec("Fairfield City Council", ["fairfield council"], "government"),
  rec("Georges River Council", ["georges river"], "government"),
  rec("City of Ryde", ["ryde council"], "government"),
  rec("Tweed Shire Council", ["tweed council"], "government"),
  rec("Coffs Harbour City Council", ["coffs harbour council"], "government"),
  rec("Port Macquarie-Hastings Council", ["port macquarie council"], "government"),
  rec("Wagga Wagga City Council", ["wagga council"], "government"),
  rec("Albury City Council", ["albury council"], "government"),
  rec("Tamworth Regional Council", ["tamworth council"], "government"),
  rec("Dubbo Regional Council", ["dubbo council"], "government"),
  rec("Orange City Council", ["orange council"], "government"),
  rec("Shoalhaven City Council", ["shoalhaven council"], "government"),
  rec("Blue Mountains City Council", ["blue mountains council"], "government"),
  rec("Byron Shire Council", ["byron council"], "government"),
  rec("Queanbeyan-Palerang Regional Council", ["queanbeyan council"], "government"),

  rec("City of Melbourne", ["melbourne city council", "melbourne council"], "government"),
  rec("City of Port Phillip", ["port phillip council"], "government"),
  rec("City of Yarra", ["yarra council"], "government"),
  rec("City of Stonnington", ["stonnington council"], "government"),
  rec("City of Boroondara", ["boroondara council"], "government"),
  rec("City of Glen Eira", ["glen eira council"], "government"),
  rec("City of Monash", ["monash council"], "government"),
  rec("City of Whitehorse", ["whitehorse council"], "government"),
  rec("City of Darebin", ["darebin council"], "government"),
  rec("Merri-bek City Council", ["moreland council", "merri bek"], "government"),
  rec("City of Hume", ["hume council"], "government"),
  rec("City of Whittlesea", ["whittlesea council"], "government"),
  rec("City of Casey", ["casey council"], "government"),
  rec("City of Greater Dandenong", ["dandenong council"], "government"),
  rec("City of Kingston", ["kingston council victoria"], "government"),
  rec("City of Brimbank", ["brimbank council"], "government"),
  rec("City of Wyndham", ["wyndham council"], "government"),
  rec("City of Melton", ["melton council"], "government"),
  rec("City of Greater Geelong", ["geelong council"], "government"),
  rec("City of Ballarat", ["ballarat council"], "government"),
  rec("City of Greater Bendigo", ["bendigo council"], "government"),
  rec("Latrobe City Council", ["latrobe council", "morwell council"], "government"),
  rec("Mornington Peninsula Shire", ["mornington peninsula council"], "government"),
  rec("Frankston City Council", ["frankston council"], "government"),
  rec("Knox City Council", ["knox council"], "government"),
  rec("City of Greater Shepparton", ["shepparton council"], "government"),
  rec("Mildura Rural City Council", ["mildura council"], "government"),
  rec("Wodonga City Council", ["wodonga council"], "government"),

  rec("Brisbane City Council", ["bcc", "brisbane council"], "government"),
  rec("City of Gold Coast", ["gold coast council", "gccc"], "government"),
  rec("Sunshine Coast Council", ["sunshine coast"], "government"),
  rec("Moreton Bay City Council", ["moreton bay council"], "government"),
  rec("Logan City Council", ["logan council"], "government"),
  rec("Ipswich City Council", ["ipswich council"], "government"),
  rec("Redland City Council", ["redland council", "redlands"], "government"),
  rec("Toowoomba Regional Council", ["toowoomba council"], "government"),
  rec("Townsville City Council", ["townsville council"], "government"),
  rec("Cairns Regional Council", ["cairns council"], "government"),
  rec("Mackay Regional Council", ["mackay council"], "government"),
  rec("Rockhampton Regional Council", ["rockhampton council"], "government"),
  rec("Bundaberg Regional Council", ["bundaberg council"], "government"),
  rec("Fraser Coast Regional Council", ["hervey bay council", "fraser coast"], "government"),
  rec("Gladstone Regional Council", ["gladstone council"], "government"),
  rec("Whitsunday Regional Council", ["whitsunday council"], "government"),

  rec("City of Perth", ["perth city council", "perth council"], "government"),
  rec("City of Stirling", ["stirling council"], "government"),
  rec("City of Wanneroo", ["wanneroo council"], "government"),
  rec("City of Joondalup", ["joondalup council"], "government"),
  rec("City of Swan", ["swan council"], "government"),
  rec("City of Melville", ["melville council"], "government"),
  rec("City of Cockburn", ["cockburn council"], "government"),
  rec("City of Gosnells", ["gosnells council"], "government"),
  rec("City of Canning", ["canning council"], "government"),
  rec("City of Fremantle", ["fremantle council"], "government"),
  rec("City of Rockingham", ["rockingham council"], "government"),
  rec("City of Mandurah", ["mandurah council"], "government"),
  rec("City of Bunbury", ["bunbury council"], "government"),
  rec("City of Albany", ["albany council"], "government"),
  rec("City of Kalgoorlie-Boulder", ["kalgoorlie council"], "government"),
  rec("Shire of Broome", ["broome council"], "government"),

  rec("City of Adelaide", ["adelaide city council", "adelaide council"], "government"),
  rec("City of Charles Sturt", ["charles sturt council"], "government"),
  rec("City of Port Adelaide Enfield", ["port adelaide enfield"], "government"),
  rec("City of Salisbury", ["salisbury council"], "government"),
  rec("City of Playford", ["playford council"], "government"),
  rec("City of Onkaparinga", ["onkaparinga council"], "government"),
  rec("City of Marion", ["marion council"], "government"),
  rec("City of Mitcham", ["mitcham council"], "government"),
  rec("City of Tea Tree Gully", ["tea tree gully council"], "government"),
  rec("City of Holdfast Bay", ["holdfast bay", "glenelg council"], "government"),
  rec("City of West Torrens", ["west torrens council"], "government"),
  rec("City of Mount Gambier", ["mount gambier council"], "government"),
  rec("City of Whyalla", ["whyalla council"], "government"),

  rec("City of Hobart", ["hobart city council", "hobart council"], "government"),
  rec("City of Launceston", ["launceston council"], "government"),
  rec("City of Clarence", ["clarence council"], "government"),
  rec("City of Glenorchy", ["glenorchy council"], "government"),
  rec("City of Devonport", ["devonport council"], "government"),
  rec("City of Burnie", ["burnie council"], "government"),

  rec("City of Darwin", ["darwin city council", "darwin council"], "government"),
  rec("City of Palmerston", ["palmerston council"], "government"),
  rec("Alice Springs Town Council", ["alice springs council"], "government"),

  rec("Auckland Council", ["auckland city council", "te kaunihera o tamaki makaurau"], "government"),
  rec("Wellington City Council", ["wcc", "wellington council"], "government"),
  rec("Christchurch City Council", ["christchurch council", "ccc nz"], "government"),
  rec("Hamilton City Council", ["hamilton council nz"], "government"),
  rec("Tauranga City Council", ["tauranga council"], "government"),
  rec("Dunedin City Council", ["dunedin council"], "government"),
  rec("Hutt City Council", ["lower hutt council", "hutt city"], "government"),
  rec("Palmerston North City Council", ["palmerston north council"], "government"),
  rec("Napier City Council", ["napier council"], "government"),
  rec("Hastings District Council", ["hastings council nz"], "government"),
  rec("New Plymouth District Council", ["new plymouth council"], "government"),
  rec("Rotorua Lakes Council", ["rotorua council"], "government"),
  rec("Whangarei District Council", ["whangarei council"], "government"),
  rec("Nelson City Council", ["nelson council nz"], "government"),
  rec("Invercargill City Council", ["invercargill council"], "government"),
  rec("Queenstown-Lakes District Council", ["queenstown council", "qldc"], "government"),
  rec("Tasman District Council", ["tasman council nz"], "government"),
  rec("Marlborough District Council", ["marlborough council"], "government"),
  rec("Porirua City Council", ["porirua council"], "government"),
  rec("Upper Hutt City Council", ["upper hutt council"], "government"),
  rec("Kapiti Coast District Council", ["kapiti council"], "government"),
  rec("Whanganui District Council", ["wanganui council", "whanganui council"], "government"),
  rec("Gisborne District Council", ["gisborne council"], "government"),
  rec("Far North District Council", ["far north council", "kerikeri council"], "government"),
  rec("Waikato District Council", ["waikato council"], "government"),
  rec("Waikato Regional Council", ["environment waikato"], "government"),
  rec("Greater Wellington Regional Council", ["gwrc"], "government"),
  rec("Environment Canterbury", ["ecan", "canterbury regional council"], "government"),
  rec("Bay of Plenty Regional Council", ["boprc"], "government"),
  rec("Otago Regional Council", ["orc nz"], "government"),
  rec("Environment Southland", ["southland regional council"], "government"),
  rec("Northland Regional Council", ["nrc nz"], "government"),
  rec("Horizons Regional Council", ["manawatu wanganui regional"], "government"),

  rec("University of Melbourne", ["unimelb"], "education"),
  rec("University of Sydney", ["usyd"], "education"),
  rec("UNSW", ["university of new south wales"], "education"),
  rec("Monash University", ["monash"], "education"),
  rec("ANU", ["australian national university"], "education"),
  rec("University of Queensland", ["uq"], "education"),
  rec("QUT", ["queensland university of technology"], "education"),
  rec("RMIT", ["rmit university"], "education"),
  rec("Deakin University", ["deakin"], "education"),
  rec("La Trobe University", ["latrobe"], "education"),
  rec("Griffith University", ["griffith"], "education"),
  rec("UTS", ["university of technology sydney"], "education"),
  rec("Macquarie University", ["mq"], "education"),
  rec("Curtin University", ["curtin"], "education"),
  rec("UWA", ["university of western australia"], "education"),
  rec("University of Adelaide", ["adelaide university"], "education"),
  rec("University of Tasmania", ["utas"], "education"),
  rec("TAFE NSW", [], "education"),
  rec("TAFE Queensland", [], "education"),
  rec("Holmesglen", [], "education"),
  rec("Department of Education NSW", ["nsw education"], "education"),
  rec("Department of Education Victoria", ["vic education"], "education"),
  rec("Department of Education Queensland", ["eq", "education queensland"], "education"),

  // Vehicle OEMs — common passenger, light-commercial and truck brands in AU/NZ
  rec("Toyota", ["toyota australia", "toyota nz"], "automotive"),
  rec("Lexus", ["lexus australia"], "automotive"),
  rec("Mazda", ["mazda australia"], "automotive"),
  rec("Hyundai", ["hyundai australia"], "automotive"),
  rec("Kia", ["kia australia"], "automotive"),
  rec("Mitsubishi", ["mitsubishi motors"], "automotive"),
  rec("Ford", ["ford australia", "ford motor"], "automotive"),
  rec("Holden", ["gm holden", "general motors holden"], "automotive"),
  rec("General Motors", ["gm australia", "chevrolet australia"], "automotive"),
  rec("Nissan", ["nissan australia"], "automotive"),
  rec("Subaru", ["subaru australia"], "automotive"),
  rec("Honda", ["honda australia"], "automotive"),
  rec("Suzuki", ["suzuki australia"], "automotive"),
  rec("Volkswagen", ["vw australia", "volkswagen group"], "automotive"),
  rec("Skoda", ["skoda australia"], "automotive"),
  rec("Audi", ["audi australia"], "automotive"),
  rec("BMW", ["bmw australia", "bmw group"], "automotive"),
  rec("Mini", ["mini australia"], "automotive"),
  rec("Mercedes-Benz", ["mercedes benz", "mercedes australia"], "automotive"),
  rec("Porsche", ["porsche australia"], "automotive"),
  rec("Volvo Cars", ["volvo australia", "volvo car"], "automotive"),
  rec("Jaguar Land Rover", ["land rover", "range rover", "jaguar australia"], "automotive"),
  rec("Jeep", ["jeep australia"], "automotive"),
  rec("RAM", ["ram trucks", "ram australia"], "automotive"),
  rec("Tesla", ["tesla australia"], "automotive"),
  rec("BYD", ["byd australia"], "automotive"),
  rec("MG", ["mg motor", "mg australia"], "automotive"),
  rec("GWM", ["great wall", "haval", "gwm haval"], "automotive"),
  rec("LDV", ["ldv automotive"], "automotive"),
  rec("Chery", ["chery australia", "omoda", "jaecoo"], "automotive"),
  rec("Isuzu", ["isuzu ute", "isuzu d-max"], "automotive"),
  rec("Isuzu Trucks", ["isuzu commercial"], "automotive"),
  rec("Hino", ["hino trucks", "hino australia"], "automotive"),
  rec("Fuso", ["mitsubishi fuso", "fuso trucks"], "automotive"),
  rec("UD Trucks", ["ud nissan diesel"], "automotive"),
  rec("Kenworth", ["kenworth trucks", "paccar kenworth"], "automotive"),
  rec("DAF", ["daf trucks"], "automotive"),
  rec("Mack", ["mack trucks"], "automotive"),
  rec("Volvo Trucks", ["volvo truck"], "automotive"),
  rec("Scania", ["scania trucks"], "automotive"),
  rec("MAN", ["man trucks"], "automotive"),
  rec("Iveco", ["iveco trucks"], "automotive"),
  rec("Freightliner", ["freightliner trucks"], "automotive"),
  rec("Western Star", ["western star trucks"], "automotive"),
  rec("Paccar", ["paccar australia"], "automotive"),
  rec("Yamaha", ["yamaha motor"], "automotive"),
  rec("Kawasaki", ["kawasaki motors"], "automotive"),
  rec("Harley-Davidson", ["harley davidson"], "automotive"),
  rec("KTM", ["ktm australia"], "automotive"),
  rec("Polaris", ["polaris australia"], "automotive"),
  rec("BRP", ["can-am", "canam", "ski-doo"], "automotive"),

  // Machinery OEMs — construction, agricultural and material-handling
  rec("Caterpillar", ["cat", "cat equipment", "caterpillar australia"], "machinery"),
  rec("Komatsu", ["komatsu australia"], "machinery"),
  rec("Hitachi Construction Machinery", ["hitachi construction", "hitachi machinery"], "machinery"),
  rec("John Deere", ["deere", "john deere australia"], "machinery"),
  rec("Case IH", ["case agriculture", "case ih australia"], "machinery"),
  rec("Case Construction", ["case ce", "case excavator"], "machinery"),
  rec("New Holland", ["new holland agriculture"], "machinery"),
  rec("Massey Ferguson", ["massey ferguson australia"], "machinery"),
  rec("Fendt", ["fendt tractor"], "machinery"),
  rec("CLAAS", ["claas australia"], "machinery"),
  rec("Kubota", ["kubota australia", "kubota tractor"], "machinery"),
  rec("Mahindra", ["mahindra tractor"], "machinery"),
  rec("JCB", ["jcb australia", "j.c. bamford"], "machinery"),
  rec("Volvo Construction Equipment", ["volvo ce", "volvo excavator"], "machinery"),
  rec("Liebherr", ["liebherr australia"], "machinery"),
  rec("Bobcat", ["bobcat australia"], "machinery"),
  rec("Yanmar", ["yanmar construction", "yanmar australia"], "machinery"),
  rec("Doosan", ["doosan bobcat", "develon"], "machinery"),
  rec("Kobelco", ["kobelco excavator"], "machinery"),
  rec("Takeuchi", ["takeuchi excavator"], "machinery"),
  rec("SANY", ["sany australia"], "machinery"),
  rec("Manitou", ["manitou australia"], "machinery"),
  rec("Terex", ["terex australia"], "machinery"),
  rec("Wirtgen", ["wirtgen group", "hamm roller", "vogele"], "machinery"),
  rec("Sandvik", ["sandvik mining"], "machinery"),
  rec("Epiroc", ["atlas copco mining"], "machinery"),
  rec("Metso", ["metso outotec"], "machinery"),
  rec("Tadano", ["tadano crane"], "machinery"),
  rec("Grove", ["manitowoc grove"], "machinery"),
  rec("Palfinger", ["palfinger crane"], "machinery"),
  rec("Hiab", ["hiab crane", "cargotec"], "machinery"),
  rec("Toyota Material Handling", ["toyota forklift", "toyota forklifts"], "machinery"),
  rec("Crown Equipment", ["crown forklift"], "machinery"),
  rec("Hyster", ["hyster forklift", "hyster-yale"], "machinery"),
  rec("Yale", ["yale forklift"], "machinery"),
  rec("Jungheinrich", ["jungheinrich forklift"], "machinery"),
  rec("STIHL", ["stihl australia"], "machinery"),
  rec("Husqvarna", ["husqvarna australia"], "machinery"),
  rec("Honda Power Equipment", ["honda mower", "honda generator"], "machinery"),

  // Professional services
  rec("PwC", ["pricewaterhousecoopers"], "professional"),
  rec("Deloitte", [], "professional"),
  rec("EY", ["ernst and young", "ernst & young"], "professional"),
  rec("KPMG", [], "professional"),
  rec("Accenture", [], "professional"),
  rec("McKinsey", ["mckinsey and company"], "professional"),
  rec("Boston Consulting Group", ["bcg"], "professional"),
  rec("Bain & Company", ["bain"], "professional"),
  rec("Capgemini", [], "professional"),
  rec("Cognizant", [], "professional"),
  rec("Hays", ["hays recruiting"], "professional"),
  rec("Robert Half", [], "professional"),
  rec("Randstad", [], "professional"),
  rec("Adecco", [], "professional"),
  rec("Programmed", [], "professional"),
  rec("Chandler Macleod", [], "professional"),

  // Construction & infrastructure
  rec("Lendlease", ["lend lease"], "construction"),
  rec("CIMIC", ["cpb contractors", "leighton"], "construction"),
  rec("CPB Contractors", ["cpb"], "construction"),
  rec("John Holland", [], "construction"),
  rec("Multiplex", [], "construction"),
  rec("Laing O'Rourke", ["laing orourke"], "construction"),
  rec("Hutchinson Builders", ["hutchies"], "construction"),
  rec("McConnell Dowell", [], "construction"),
  rec("Downer", ["downer edi"], "construction"),
  rec("Ventia", [], "construction"),
  rec("Transurban", [], "construction"),
  rec("Broadspectrum", ["ventia broadspectrum"], "construction"),
  rec("Mirvac", [], "construction"),
  rec("Stockland", [], "construction"),
  rec("GPT", [], "construction"),
  rec("Scentre Group", ["westfield"], "retail"),
  rec("Westfield", [], "retail"),

  // Airlines, travel, logistics
  rec("Qantas", ["qantas airways"], "aviation"),
  rec("Jetstar", [], "aviation"),
  rec("Virgin Australia", ["virgin"], "aviation"),
  rec("Rex", ["regional express"], "aviation"),
  rec("Airservices Australia", [], "aviation"),
  rec("Toll", ["toll group"], "logistics"),
  rec("Linfox", [], "logistics"),
  rec("Team Global Express", ["tge"], "logistics"),
  rec("StarTrack", ["star track"], "logistics"),
  rec("FedEx", [], "logistics"),
  rec("DHL", [], "logistics"),
  rec("TNT", [], "logistics"),
  rec("Aurizon", [], "logistics"),
  rec("Pacific National", [], "logistics"),
  rec("Mainfreight", [], "logistics"),
  rec("Qube", ["qube logistics"], "logistics"),

  // Hospitality & food
  rec("McDonald's", ["mcdonalds", "maccas"], "hospitality"),
  rec("Hungry Jack's", ["hungry jacks", "burger king"], "hospitality"),
  rec("KFC", ["kfc australia"], "hospitality"),
  rec("Subway", [], "hospitality"),
  rec("Domino's", ["dominos"], "hospitality"),
  rec("Pizza Hut", [], "hospitality"),
  rec("Grill'd", ["grilld"], "hospitality"),
  rec("Guzman y Gomez", ["gyg"], "hospitality"),
  rec("Nando's", ["nandos"], "hospitality"),
  rec("Red Rooster", [], "hospitality"),
  rec("Coffee Club", [], "hospitality"),
  rec("Gloria Jean's", ["gloria jeans"], "hospitality"),
  rec("Starbucks", ["starbucks australia"], "hospitality"),
  rec("Boost Juice", [], "hospitality"),
  rec("Guzman", [], "hospitality"),
  rec("Accor", ["ibis", "novotel", "mercure", "pullman"], "hospitality"),
  rec("Hilton", ["hilton australia"], "hospitality"),
  rec("Marriott", ["marriott australia"], "hospitality"),
  rec("Mantra", ["mantra hotels"], "hospitality"),
  rec("Quest Apartments", ["quest"], "hospitality"),
  rec("IHG", ["holiday inn", "crowne plaza"], "hospitality"),
  rec("Club Med", [], "hospitality"),
  rec("Flight Centre", ["fctg"], "travel"),
  rec("Webjet", [], "travel"),
  rec("Helloworld", [], "travel"),

  // Media & telco-adjacent
  rec("Nine", ["nine entertainment", "channel 9"], "media"),
  rec("Seven", ["seven west", "channel 7"], "media"),
  rec("Ten", ["paramount ten", "channel 10"], "media"),
  rec("News Corp", ["news limited", "the australian"], "media"),
  rec("Nine Newspapers", ["smh", "the age"], "media"),
  rec("Foxtel", [], "media"),

  // Other large employers
  rec("Wesfarmers", [], "retail"),
  rec("Woolworths Group", [], "retail"),
  rec("Coles Group", [], "retail"),
  rec("Aristocrat", ["aristocrat leisure"], "other"),
  rec("Carsales", ["carsales.com.au"], "other"),
  rec("REA Group", ["realestate.com.au"], "other"),
  rec("Seek", [], "other"),
  rec("Domain", [], "other"),
  rec("Coates Hire", ["coates"], "other"),
  rec("Kennards Hire", ["kennards"], "other"),
  rec("Boral", [], "construction"),
  rec("CSR", [], "construction"),
  rec("James Hardie", [], "construction"),
  rec("BlueScope", ["bluescope steel"], "resources"),
  rec("Orica", [], "resources"),
  rec("Incitec Pivot", ["incitec"], "resources"),
  rec("Treasury Wine Estates", ["penfolds", "wolf blass"], "other"),
  rec("Coca-Cola Europacific Partners", ["coca cola", "coke"], "other"),
  rec("Lion", ["tooheys", "xxxx"], "other"),
  rec("Asahi", ["carlton draught", "great northern"], "other"),
  rec("Unilever", [], "other"),
  rec("Procter & Gamble", ["pg"], "other"),
  rec("Nestlé", ["nestle"], "other"),
  rec("Fonterra", [], "other"),
  rec("a2 Milk", ["a2"], "other"),
  rec("ResMed", [], "health"),
];

function present(row) {
  return { name: row.name, sector: row.sector || "" };
}

function scoreEmployer(row, q) {
  const name = row.name.toLowerCase();
  if (name === q) return 120;
  if (name.startsWith(q)) return 100;
  if (name.includes(q)) return 80;
  for (const a of row.aliases || []) {
    if (a === q) return 110;
    if (a.startsWith(q)) return 90;
    if (a.includes(q)) return 65;
  }
  if ((row.sector || "").includes(q)) return 30;
  return 0;
}

function searchEmployers(query, { limit = 20 } = {}) {
  const q = String(query || "")
    .trim()
    .toLowerCase();
  const cap = Math.min(40, Math.max(1, Number(limit) || 20));
  if (!q) {
    return EMPLOYERS.slice(0, cap).map(present);
  }
  const scored = [];
  for (const row of EMPLOYERS) {
    const score = scoreEmployer(row, q);
    if (score > 0) scored.push({ row, score });
  }
  scored.sort((a, b) => b.score - a.score || a.row.name.localeCompare(b.row.name));
  return scored.slice(0, cap).map(({ row }) => present(row));
}

function listEmployers() {
  return EMPLOYERS.map(present);
}

module.exports = {
  EMPLOYERS,
  searchEmployers,
  listEmployers,
};
